name: constellation_catcher
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.3+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

  # ui
  another_flushbar: ^1.12.30
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0

  # icons
  flutter_vector_icons: ^2.0.0
  animate_icons: ^2.0.0
  cupertino_icons: ^1.0.8

  # network
  dio: ^5.4.1

  # utils
  logging: ^1.2.0
  url_launcher: ^6.0.3
  equatable: ^2.0.7
  share_plus: ^10.0.3

  # animation
  flutter_animate: ^4.1.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0

  # storage
  shared_preferences: ^2.2.2

  # state management
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_rating_bar: ^4.0.1

  # annotations
  freezed_annotation: ^2.1.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5

  # database
  drift: ^2.20.2
  drift_flutter: ^0.2.0

  firebase_core: ^3.9.0
  firebase_analytics: ^11.3.3

  rive: ^0.13.18
  go_router: ^14.6.1
  just_audio: ^0.9.42
  google_mobile_ads: ^5.2.0
  forge2d: ^0.13.1
  flame: ^1.26.1
  flame_forge2d: ^0.18.3

  flutter_dotenv: ^5.2.1
  window_manager: ^0.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  freezed: ^2.3.0
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  drift_dev: ^2.20.3

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/audio/

assets_dir: "assets"
assets_output_file: "lib/config/assets.dart"
assets_class_name: "Assets"
